### PR TITLE
Make xScale and yScale available in Chart context

### LINKED ISSUE #21: Use react context for yScale/xScale?
Seems a little awkward to have to pass that into every child component manually, since probably 99% of the time it's going to be all the same.

### PR DESCRIPTION
**Pull request by skeate**
Closes #21

### CODE REVIEW

**Comment by jameslaneconkling** [comment]
I had originally set it up this way, but ran into the following issues:
* props passed from parent to child were not available at render time.  I implemented sharing of scales slightly differently, see [this commit](https://github.com/jameslaneconkling/yard3/commit/61b5f90cba5adadbbc0395c8e20dbac92810e73b) that removed it.
  * b/c of above, props couldn't be validated w/ propTypes
* there are cases where you might want to pass different scales to subcomponents, e.g. [here](https://jameslaneconkling.github.io/yard3/#!/Chart/1), where the axes use one set of scales, and the grid lines use another.  Or, e.g. a [dual scale chart](https://github.com/liufly/Dual-scale-D3-Bar-Chart/blob/master/preview/thumbnail.png).

It could be that your approach (using context type, rather than yielding additional properties to child components) doesn't run into the first two issues, will test out.  And I assume properties passed as context type can be overwritten by properties passed explicitly (need to check).

Assuming the above points aren't issues, I'll merge.  Give me a sec to test it out.

**Comment by skeate** [comment]
Not entirely sure what you were doing before -- looks like you cloned the children and manually inserted the `xScale` and `yScale`? This uses the built-in `contextTypes` mechanism, so it shouldn't have any issues. I also changed the styleguide and was running that to test that it worked.

The second point shouldn't be an issue, as with my PR it will always prioritize (e.g.) `this.props.xScale` over `this.context.xScale`, if `this.props.xScale` exists:

```
const xScale = this.props.xScale || this.context.xScale;
```

**Comment by skeate** [comment]
The only downside I see is that it's possible to forget to pass in `xScale` or `yScale`, and you won't get a warning about it being required, since it no longer is truly _required_ in any one place (since `Chart` doesn't need it if doing a pie chart, for example)

**Comment by skeate** [comment]
I think I might see what you are talking about in the first bullet, but I think it's still related to the whole `cloneElement` thing.

**Comment by skeate** [comment]
So I removed it entirely!

**Comment by jameslaneconkling** [comment]
yeah, the 

```javascript
React.Children.map(children, (child) => React.cloneElement(child, { ...otherProps });
```

is I think the recommended way to yield properties from a parent to a child (or at least based on this [SO answer](http://stackoverflow.com/questions/32370994/how-to-pass-props-to-this-props-children)).  But I think you're right, b/c when using `contextType`, those props are available at render.

I'll look the PR over one last time this morning and merge.

**Comment by skeate** [comment]
Missed one.

**Comment by skeate** [comment]
That SO post is old (in Javascript terms) -- there's a newer answer below that uses context.

**Comment by jameslaneconkling** [comment]
yeah, but I kind of agreed (at the time at least) w/ the "it's experimental and likely to break w/ future releases" [warning comment](https://facebook.github.io/react/docs/context.html).

Now, I'm less sure.  I think they just want to make sure people don't abuse it.

**Pull request merged**
